[project]
name = "optimal_morphology_rl"
version = "0.1.0"
authors = [{ name = "Valentin Yuryev", email = "valentin.yuryev@gmail.com" }]
maintainers = [{ name = "Valentin Yuryev", email = "valentin.yuryev@gmail.com" }]
description = "RL to find optimal morphology"
readme = "README.md"
requires-python = "==3.10.19"
dependencies = [
    "torch==2.9.0+cu129",
    "torchvision==0.24.0+cu129",
    "torchaudio==2.9.0+cu129",
    "vlearn",
    "rl_games",
    "matplotlib",
    "pyyaml",
    "tensorboard",
    "h5py",
    "gymnasium>=1.2.2",
    "wandb>=0.23.1",
    "vlearn_train",
]

[tool.uv.sources]
torch = { index = "pytorch-cu129"}
torchvision = { index = "pytorch-cu129"}
torchaudio = { index = "pytorch-cu129"}
vlearn = { path = "./tools/vlearn/vlearn-0.3.0-cp310-cp310-linux_x86_64.whl" }
rl_games = { path = "./tools/rl_games", editable = true }
vlearn_train = { workspace = true, editable = true }

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"

[tool.uv.workspace]
members = [
    "tools/vlearn",
]
